name: BanditQuests
version: 2.0.0
main: me.semmmetje.banditquests.BanditQuests
api-version: '1.21'
author: semmmetjeee
softdepend: [BanditKills]
commands:
  saloonboard:
    description: Open the Saloon Board
    aliases: [jobs, quests]
    permission: banditquests.use
  banditquests:
    description: Manage BanditQuests
    usage: /banditquests reload
    permission: banditquests.admin
permissions:
  banditquests.use:
    default: true
  banditquests.admin:
    default: op
