package me.semmmetje.banditquests;

import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.configuration.ConfigurationSection;import org.bukkit.configuration.file.YamlConfiguration;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.block.BlockBreakEvent;import org.bukkit.event.entity.EntityDeathEvent;import org.bukkit.event.entity.PlayerDeathEvent;import org.bukkit.event.inventory.InventoryClickEvent;import org.bukkit.event.player.*;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import org.bukkit.plugin.java.JavaPlugin;import java.io.File;import java.io.IOException;import java.time.*;import java.util.*;import java.util.regex.Matcher;import java.util.regex.Pattern;

public final class BanditQuests extends JavaPlugin implements Listener,CommandExecutor {
 private static final Pattern HEX=Pattern.compile("&#([A-Fa-f0-9]{6})");
 private final Map<String,Quest> quests=new LinkedHashMap<>(); private final Map<UUID,Data> data=new HashMap<>(); private File folder; private YamlConfiguration gui;
 record Quest(String id,String type,int goal,int marks,String name,String description){}
 static final class Data {String day="";List<String> jobs=new ArrayList<>();Map<String,Integer> progress=new HashMap<>();Set<String> claimed=new HashSet<>();}
 public void onEnable(){saveDefaultConfig();saveResource("quests.yml",false);saveResource("gui.yml",false);folder=new File(getDataFolder(),"players");folder.mkdirs();loadQuests();gui=YamlConfiguration.loadConfiguration(new File(getDataFolder(),"gui.yml"));Objects.requireNonNull(getCommand("saloonboard")).setExecutor(this);getServer().getPluginManager().registerEvents(this,this);getServer().getScheduler().runTaskTimer(this,()->Bukkit.getOnlinePlayers().forEach(p->progress(p,"PLAY_MINUTES",1)),1200,1200);}
 private void loadQuests(){YamlConfiguration q=YamlConfiguration.loadConfiguration(new File(getDataFolder(),"quests.yml"));ConfigurationSection root=q.getConfigurationSection("quests");if(root==null)return;for(String id:root.getKeys(false)){ConfigurationSection s=root.getConfigurationSection(id);if(s!=null)quests.put(id,new Quest(id,s.getString("type","LOGIN"),s.getInt("goal",1),s.getInt("marks",1),s.getString("name",id),s.getString("description","")));}}
 private String today(){return LocalDate.now(ZoneId.of(getConfig().getString("reset-timezone","Europe/Amsterdam"))).toString();}
 private Data get(Player p){Data d=data.computeIfAbsent(p.getUniqueId(),this::load);if(!d.day.equals(today())){d.day=today();List<String> ids=new ArrayList<>(quests.keySet());Collections.shuffle(ids,new Random(p.getUniqueId().hashCode()^d.day.hashCode()));d.jobs=new ArrayList<>(ids.subList(0,Math.min(getConfig().getInt("daily-quests",3),ids.size())));d.progress.clear();d.claimed.clear();save(p,d);}return d;}
 private Data load(UUID id){YamlConfiguration y=YamlConfiguration.loadConfiguration(new File(folder,id+".yml"));Data d=new Data();d.day=y.getString("day","");d.jobs=y.getStringList("jobs");for(String key:y.getConfigurationSection("progress")==null?List.<String>of():y.getConfigurationSection("progress").getKeys(false))d.progress.put(key,y.getInt("progress."+key));d.claimed.addAll(y.getStringList("claimed"));return d;}
 private void save(Player p,Data d){YamlConfiguration y=new YamlConfiguration();y.set("day",d.day);y.set("jobs",d.jobs);d.progress.forEach((k,v)->y.set("progress."+k,v));y.set("claimed",new ArrayList<>(d.claimed));try{y.save(new File(folder,p.getUniqueId()+".yml"));}catch(IOException e){getLogger().warning(e.getMessage());}}
 private void progress(Player p,String type,int amount){Data d=get(p);for(String id:d.jobs){Quest q=quests.get(id);if(q!=null&&q.type.equals(type)&&!d.claimed.contains(id))d.progress.merge(id,amount,Integer::sum);}save(p,d);}
 @EventHandler public void join(PlayerJoinEvent e){get(e.getPlayer());progress(e.getPlayer(),"LOGIN",1);}
 @EventHandler public void death(PlayerDeathEvent e){Player k=e.getEntity().getKiller();if(k!=null)progress(k,"KILL_PLAYER",1);}
 @EventHandler public void mob(EntityDeathEvent e){Player k=e.getEntity().getKiller();if(k!=null&&!(e.getEntity() instanceof Player))progress(k,"KILL_MOB",1);}
 @EventHandler public void mine(BlockBreakEvent e){String t=switch(e.getBlock().getType()){case GOLD_ORE,DEEPSLATE_GOLD_ORE->"MINE_GOLD";case DIAMOND_ORE,DEEPSLATE_DIAMOND_ORE->"MINE_DIAMOND";case ANCIENT_DEBRIS->"MINE_ANCIENT_DEBRIS";default->"";};if(!t.isEmpty())progress(e.getPlayer(),t,1);}
 @EventHandler public void fish(PlayerFishEvent e){if(e.getState()==PlayerFishEvent.State.CAUGHT_FISH)progress(e.getPlayer(),"FISH",1);}
 public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(!(s instanceof Player p)){return true;}open(p);return true;}
 private void open(Player p){Data d=get(p);Inventory inv=Bukkit.createInventory(new Holder(),45,color(gui.getString("title","Saloon Board")));Material border=Material.matchMaterial(gui.getString("border.material","BLACK_STAINED_GLASS_PANE"));for(int i=0;i<45;i++)if(i<9||i>=36||i%9==0||i%9==8)inv.setItem(i,item(border==null?Material.BLACK_STAINED_GLASS_PANE:border," ",List.of()));inv.setItem(gui.getInt("info.slot",4),item(Material.CLOCK,gui.getString("info.name","Jobs"),gui.getStringList("info.lore")));List<Integer> slots=gui.getIntegerList("job.slots");for(int i=0;i<d.jobs.size()&&i<slots.size();i++){Quest q=quests.get(d.jobs.get(i));if(q==null)continue;int pg=Math.min(q.goal,d.progress.getOrDefault(q.id,0));boolean claim=d.claimed.contains(q.id),done=pg>=q.goal;String st=claim?gui.getString("status.claimed"):done?gui.getString("status.complete"):gui.getString("status.incomplete");Material m=Material.matchMaterial(gui.getString("job."+(claim?"claimed-material":done?"complete-material":"incomplete-material"),"PAPER"));Map<String,String> v=Map.of("name",q.name,"description",q.description,"progress",""+pg,"goal",""+q.goal,"marks",""+q.marks,"status",st);inv.setItem(slots.get(i),item(m==null?Material.PAPER:m,replace(gui.getString("job.name"),v),gui.getStringList("job.lore").stream().map(x->replace(x,v)).toList()));}p.openInventory(inv);}
 @EventHandler public void click(InventoryClickEvent e){if(!(e.getInventory().getHolder() instanceof Holder)||!(e.getWhoClicked() instanceof Player p)){return;}e.setCancelled(true);int index=gui.getIntegerList("job.slots").indexOf(e.getRawSlot());if(index<0)return;Data d=get(p);if(index>=d.jobs.size())return;Quest q=quests.get(d.jobs.get(index));if(q==null)return;if(d.claimed.contains(q.id)){msg(p,"already-claimed",Map.of());return;}if(d.progress.getOrDefault(q.id,0)<q.goal){msg(p,"not-complete",Map.of());return;}d.claimed.add(q.id);save(p,d);String command=getConfig().getString("reward-command","").replace("%player%",p.getName()).replace("%marks%",""+q.marks);if(!command.isBlank())Bukkit.dispatchCommand(Bukkit.getConsoleSender(),command);msg(p,"claimed",Map.of("marks",""+q.marks));open(p);}
 record Holder() implements InventoryHolder{public Inventory getInventory(){return null;}}
 private ItemStack item(Material m,String n,List<String> l){ItemStack s=new ItemStack(m);ItemMeta x=s.getItemMeta();x.setDisplayName(color(n));x.setLore(l.stream().map(this::color).toList());s.setItemMeta(x);return s;}
 private String replace(String x,Map<String,String> v){for(var e:v.entrySet())x=x.replace("%"+e.getKey()+"%",e.getValue());return x;}
 private String color(String s){Matcher matcher=HEX.matcher(s==null?"":s);StringBuffer out=new StringBuffer();while(matcher.find())matcher.appendReplacement(out,Matcher.quoteReplacement(net.md_5.bungee.api.ChatColor.of("#"+matcher.group(1)).toString()));matcher.appendTail(out);return ChatColor.translateAlternateColorCodes('&',out.toString());}
 private void msg(Player p,String key,Map<String,String> v){String x=getConfig().getString("messages."+key,"");for(var e:v.entrySet())x=x.replace("%"+e.getKey()+"%",e.getValue());p.sendMessage(color(x.replace("%prefix%",getConfig().getString("messages.prefix",""))));}
}